{{- if ne .Values.image.registry "local" }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: opal-worker-v2-secret
    creationPolicy: Owner
  data:
    - secretKey: OPAL_WORKER_TOKEN
      remoteRef:
        key: opal-secret
        property: OPAL_WORKER_TOKEN
{{- end }}
