config:
  env:
    OPAL_REDIS_URL: "redis://replication-group-v2-6269ee4-001.wkxvxw.0001.use2.cache.amazonaws.com:6379"
    OPAL_SERVER_URL: "https://opal-v2.permit.io"
  envRef:
    DD_AGENT_HOST:
      name: status.hostIP

mounts:
  - type: "efs"
    storageClass: "efs-sc"
    name: "scopes-mount-worker"
    size: "20Gi"
    fileSystemId: "fs-0943e43818f70b8e5"
    path: "/opal/git_sources"

labels_all:
  tags.datadoghq.com/env: "k8s-prod-v2"

annotations_template:
  ad.datadoghq.com/opal-worker-v2.logs: '[{"type":"file", "path": "logs/output-opal-worker-*.log", "source":"{{ .Release.Name }}-prod-k8s"}]'
