raw_docker_image: 076477451822.dkr.ecr.us-east-2.amazonaws.com/opal-server-v2:next
name: opal-worker

config:
  envSecrets:
    OPAL_WORKER_TOKEN:
      name: opal-worker-v2-secret
      key: OPAL_WORKER_TOKEN

  env:
    OPAL_REDIS_URL: "redis://replication-group-v2-6269ee4-001.wkxvxw.0001.use2.cache.amazonaws.com:6379"
    OPAL_SCOPES: "1"
    OPAL_SERVER_URL: "https://opal-v2.permit.io"
    OPAL_BASE_DIR: "/opal"
    OPAL_POLICY_REFRESH_INTERVAL: "60"
  envRef:
    DD_AGENT_HOST:
      name: status.hostIP
    DD_ENV:
      name: metadata.labels['tags.datadoghq.com/env']
    DD_SERVICE:
      name: metadata.labels['tags.datadoghq.com/service']
    DD_VERSION:
      name: metadata.labels['tags.datadoghq.com/version']

mounts:
  - type: "efs"
    storageClass: "efs-sc"
    name: "scopes-mount-worker"
    size: "20Gi"
    fileSystemId: "fs-0943e43818f70b8e5"
    path: "/opal/git_sources"

raw_container:
  command: [ "/bin/sh","-c" ]
  args: ["celery -A opal_server.worker worker -B --concurrency=1 -l info -s /tmp/schedule.db" ]


labels_all:
  tags.datadoghq.com/env: "k8s-prod-v2"
  tags.datadoghq.com/service: "{{ .Chart.Name }}"
  tags.datadoghq.com/version: "{{ .Release.Name }}"

annotations_template:
  ad.datadoghq.com/opal-worker-v2.logs: '[{"source":"{{ .Chart.Name }}-prod-k8s"}]'
