name: opal-worker
image:
  name: permit-opal-worker-v2

config:
  envSecrets:
    OPAL_WORKER_TOKEN:
      name: opal-worker-v2-secret
      key: OPAL_WORKER_TOKEN

  env:
    OPAL_REDIS_URL: "redis://replication-group-cd782ff-001.xqxfy0.0001.use2.cache.amazonaws.com:6379"
    OPAL_SCOPES: "1"
    OPAL_SERVER_URL: "https://opal-v2.stg.permit.io"
    OPAL_AMQP_EXCHANGE_NAME: "topic-stg"
    OPAL_BASE_DIR: "/opal"
    OPAL_POLICY_REFRESH_INTERVAL: "60"
    OPAL_LOG_TO_FILE: "True"
    OPAL_LOG_FILE_PATH: "git_sources/output.log"
  envRef:
    DD_ENV:
      name: metadata.labels['tags.datadoghq.com/env']
    DD_SERVICE:
      name: metadata.labels['tags.datadoghq.com/service']
    DD_VERSION:
      name: metadata.labels['tags.datadoghq.com/version']

mounts:
  - type: "efs"
    storageClass: "efs-sc"
    name: "scopes-mount-worker"
    size: "20Gi"
    fileSystemId: "fs-009b9609b317e2927"
    path: "/opal/git_sources"

raw_container:
  command: [ "/bin/sh","-c" ]
  args: ["celery -A opal_server.worker worker -B --concurrency=1 -l info -s /tmp/schedule.db" ]

labels_all:
  tags.datadoghq.com/env: "k8s-stg-v2"
  tags.datadoghq.com/service: "{{ .Release.Name }}"
  tags.datadoghq.com/version: "{{ .Values.image.tag }}"

annotations_template:
  ad.datadoghq.com/opal-worker-v2.logs: '[{"type":"file", "path": "logs/output-opal-worker-*.log", "source":"{{ .Release.Name }}-stg-k8s"}]'
