raw_docker_image: docker.io/permitio/opal-server:latest

config:
  envSecrets: null
  env:
    OPAL_WORKER_TOKEN: "token"
    OPAL_REDIS_URL: "redis://redis-master.{{ .Release.Namespace }}.svc"
    OPAL_SERVER_URL: "http://opal-server.{{ .Release.Namespace }}.svc:7002/"
    OPAL_AMQP_EXCHANGE_NAME: "topic-dev"
    OPAL_LOG_TO_FILE: "False"
  envRef:
    DD_AGENT_HOST:
      name: status.hostIP

mounts:
    - name: opal-data
      path: "/opal"
      mountPath: "/opal/git_sources"
      type: "hostPath"

labels_all:
  tags.datadoghq.com/env: "k8s-dev-v2"

annotations_template:
  ad.datadoghq.com/opal-worker-v2.logs: '[{"type":"file", "path": "logs/output-opal-worker-*.log", "source":"{{ .Release.Name }}-dev-k8s"}]'
