name: Deploy to Production
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  update-deployments:
    runs-on: ubuntu-latest
    steps:
      # Checkout our repo to extract commit info
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get commit msg
      # This is for creating the version update PR to permit-deployments,
      #   do it here to avoid checking out backend's repo again
      id: extract-commit-msg
      run: |
        echo "::set-output name=commit-msg-title::$(git log -1 --pretty=%B | cat | head -n 1)"
        COMMIT_MSG=$(git log -1 --pretty=%B | cat)
        COMMIT_MSG="${COMMIT_MSG//'%'/'%25'}"
        COMMIT_MSG="${COMMIT_MSG//$'\n'/'%0A'}"
        COMMIT_MSG="${COMMIT_MSG//$'\r'/'%0D'}"
        echo "::set-output name=commit-msg::$COMMIT_MSG"

    - uses: actions/checkout@v3
      with:
        repository: permitio/permit-deployments
        ref: main
        token: ${{ secrets.GH_TOKEN }}

    - name: Update production tracked revision
      uses: mikefarah/yq@master
      with:
        cmd: yq eval -i '.prod.opal-git-ref = "${{ github.sha }}"' './versions.yaml'

    - name: Update production documentary link to commit
      uses: mikefarah/yq@master
      with:
        cmd: yq eval -i '.prod.opal-git-link = "https://github.com/permitio/opal-private/commit/${{ github.sha }}"' './versions.yaml'

    - name: Create PR for permit-deployments
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        export SHORT_SHA=${FULL_SHA::7}
        export BRANCH=auto-update/opal_$SHORT_SHA
        git checkout -b $BRANCH
        git commit -a -F- <<EOF
        Update opal-private: "${{ steps.extract-commit-msg.outputs.commit-msg-title }}" ($SHORT_SHA)

        ${{ steps.extract-commit-msg.outputs.commit-msg }}
        production's opal version upgraded to $FULL_SHA : https://github.com/permitio/opal-private/commit/$FULL_SHA
        This commit is auto-generated by Github Actions workflow of opal-private
        EOF
        git push --set-upstream origin $BRANCH
        gh pr create --fill --reviewer "$GITHUB_ACTOR"
      env:
        FULL_SHA: ${{ github.sha }}
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

    - name: Automatically merge PR
      # To achieve full CI/CD - turn this on
      if: ${{ true }}
      run: |
        gh pr merge

  update-staging:
    # On push to master - trigger sync of permit-deployments so staging would be deployed with new version
    if: ${{ !failure() && !cancelled() && github.ref == 'refs/heads/private' && github.event_name == 'push' }}
    needs: [test-code, test-docker, build]
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Deployments Sync
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'permitio',
            repo: 'permit-deployments',
            workflow_id: 'sync.yml',
            ref: 'main'
          })
